---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: ospcloud
    register: r_serv_info
    ignore_errors: yes
    
  - debug: var=r_serv_info
  
  - name: Delete instances 1
    os_server:
      cloud: ospcloud
      name: frontend
      state: absent
    ignore_errors: yes

  - name: Delete instances 2
    os_server:
      cloud: ospcloud
      name: app1
      state: absent
    ignore_errors: yes

  - name: Delete instances 3
    os_server:
      cloud: ospcloud
      name: app2
      state: absent
    ignore_errors: yes

  - name: Delete instances 4
    os_server:
      cloud: ospcloud
      name: db
      state: absent
    ignore_errors: yes

