---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: ospcloud
      server: app*
      filters:
        vm_statess: active
    register: r_serv_info
  - debug: var=r_serv_info
  
#  - name: Delete instances
   
