- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke
      
  - name: Curl website
    command: curl "http://{{item.public_v4}}"
    with_items:
       - "{{ openstack_info.ansible_facts.openstack_servers }}"
    register: webpage
    
  - debug: var=webpage.results[0]
      
  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible Deployed' not in webpage.results.stdout"
    tags:
      - osp.smoke
