---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
      cloud: ospcloud
      name: "{{ item.value.name }}"
      image: rhel-guest
      meta: "group={{ item.value.meta.group }},deployment_name={{ item.value.meta.deployment_name }}"
      flavor: "{{ item.value.flavor }}"
      security_groups: "{{ item.value.security_group }}"
      key_name: "{{ item.value.key_name }}"
      wait: yes
      state: "{{ item.value.state }}"
      nics:
      - net-name: int_network
  with_dict: "{{osp_servers}}"
  register: instanceip

- name: Add floating IP to Servers
  os_floating_ip:
      cloud: ospcloud
      state: present
      reuse: yes
      server: "{{ item.value.name }}"
      network: ext_network
      wait: true
      timeout: 180
  with_dict: "{{osp_servers}}"
  register: instancefloatingip

- name: Wait for server to be available
